### ISSUE TITLE
Opening setup page errors out

### ISSUE THREAD

**Issue by jjw24** [ivanipenburg/Flow.Launcher.Plugin.GoogleCalendar#37]
Hey how's it going? Just a quick one:

Opening the setup page result errors out.
![image](https://user-images.githubusercontent.com/26427004/205175478-8efe9928-a43a-4106-9736-aa46bfd68c66.png)

**Comment by ivanipenburg** [comment]
Hi! Thanks for testing the plugin. 

The problem is the text showing up in the input window right? I can't reproduce this on my side. Are you on Windows? And I don't know if you set up your credentials, but if so does this also happen for other messages?

**Comment by jjw24** [comment]
Hi yes, I meant pressing on that result will error out, I haven't tested other functions, just that one.

No once you do a new release it will be automatically updated so no need for new pr.
